adminProgrammingGame/adminProgrammingGame/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.contrib import admin

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
	url(r'^api', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('gameProgramming.urls'))
]

adminProgrammingGame/gameProgramming/urls.py
from django.conf.urls import url

from .views import GameListView
from .views import LevelDetailView


urlpatterns = [
	url(r'^$', GameListView.as_view()),
	url(r'^(?P<pk>[-\w]+)/$', LevelDetailView.as_view(), name='level-detail'),
	#url(r'^games/$', views.game_list),
	#url(r'^games/(?P<pk>[0-9]+)/$', views.game_detail),
]

adminProgrammingGame/gameProgramming/models.py
from __future__ import unicode_literals

from django.db import models


class Game(models.Model):
	name = models.CharField(max_length = 100)
	description = models.TextField(max_length = 200)

class Level(models.Model):
	game = models.ForeignKey(
		Game, 
		models.SET_NULL,
		blank = True,
		null = True,
	)

	name = models.CharField(max_length = 100)
	description = models.TextField(max_length = 200)
	order = models.IntegerField()
	instruction = models.TextField(max_length = 500)
	gameMap = models.TextField(max_length = 500)
	player = models.CharField(max_length = 200)
	target = models.CharField(max_length = 200)
	
	nextLevel = models.ForeignKey(
		"self", 
		models.SET_NULL,
		blank = True,
		null = True,
	)

	def __str__(self):
		return '%s. %s' % (self.id, self.name)

class control(models.Model):
	name = models.CharField(max_length = 30)
	level = models.ForeignKey(
		Level,
		models.SET_NULL,
		blank = True,
		null = True,
	)
	def __str__(self):
		return '%s %s' % (self.level, self.name)

class FeedBack(models.Model):
	level = models.ForeignKey(
		Level, 
		models.SET_NULL,
		blank = True,
		null = True,
	)
	description = models.TextField(max_length = 200)
	order = models.IntegerField()

adminProgrammingGame/gameProgramming/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from gameProgramming.models import *
from gameProgramming.serializers import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

class GameListView(ListView):
	
	model = Game

	def get_context_data(self, **kwargs):
		context = super(GameListView, self).get_context_data(**kwargs)
		return context

class LevelDetailView(DetailView):

	model = Level

	def get_context(self, **kwargs):
		context = super(LevelDetailView, self).get_context_data(**kwargs)
		return context

class JSONResponse(HttpResponse):
	"""
	Renderiza contenido en JSON
	"""

	def __init__(self, data, **kwargs):
		content = JSONRenderer().render(data)
		kwargs['content_type'] = 'application/json'
		super(JSONResponse, self).__init__(content, **kwargs)

	@csrf_exempt
	def game_list(request):
		"""
		Lista todos los juegos o crea uno
		"""
		if request.method == 'GET':
			games = Game.objects.all()
			serializer = GameSerializer(games, many=True)
			return JSONResponse(serializer.data)

		elif request.method == 'POST':
			data = JSONParser().parse(request)
			serializer = GameSerializer(data=data)
			if serializer.is_valid():
				serializer.save()
				return JSONResponse(serializer.data, status=201)
			return JSONResponse(serializer.errors, status=400)

	@csrf_exempt
	def game_detail(request, pk):
		"""
		Retrieve, update or delete a game.
		"""
		try:
			game = Game.objects.get(pk=pk)
		except game.DoesNotExist:
			return HttpResponse(status=404)

		if request.method == 'GET':
			serializer = GameSerializer(game)
			return JSONResponse(serializer.data)

		elif request.method == 'PUT':
			data = JSONParser().parse(request)
			serializer = GameSerializer(game, data=data)
			if serializer.is_valid():
				serializer.save()
				return JSONResponse(serializer.data)
			return JSONResponse(serializer.errors, status=400)

		elif request.method == 'DELETE':
			game.delete()
			return HttpResponse(status=204)


			

adminProgrammingGame/gameProgramming/templates/gameProgramming/game_list.html
{% load staticfiles %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<script src = "{% static "gameProgramming/lib/js/jquery-1.12.2.min.js" %}"  type="text/javascript"></script>
<script src = "{% static "gameProgramming/lib/js/material.min.js" %}"  type="text/javascript"></script>
<link rel = "stylesheet" href = "{% static "gameProgramming/lib/css/material.min.css" %}"></link>
<link rel = "stylesheet" href = "{% static "gameProgramming/statics/css/style.css" %}"></link>
<link rel = "stylesheet" href = "{% static "gameProgramming/lib/font/icons.css" %}"></link>

<body>
	
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	  <header class="mdl-layout__header">
	    <div class="headDiv mdl-layout__header-row">

	    </div>
	  </header>
	  
	  <main class="contDiv mdl-layout__content">
	    <div class="mdl-grid">
	    	<div class="mdl-cell mdl-cell--2-col"></div>
	    	<div class="mdl-cell mdl-cell--8-col">
	    		{% for game in game_list %}
	    		
		    		<div id="content">

			    		<div class="game_content">
			    			<div class="mdl-grid">
			    				<div class="mdl-cell mdl-cell--1-col gc">
			    					<div class="game_content_image image--offset">
			    						<img src="http://icons.iconarchive.com/icons/thehoth/seo/256/seo-web-code-icon.png"></img>
			    					</div>
			    				</div>

			    				<div class="mdl-cell mdl-cell--11-col gc">
			    					<div class="game_data">
					    				<span id="game_name">{{ game.name }}</span>

					    				<p id="game_description">{{ game.description }}</p>
					    			</div>
			    				</div>
			    			</div>

			    			
			    			
			    		</div>

			    		<div class="detail_content">
			    			<ul class="detail_content_list">
				    			{% for level in game.level_set.all %}
					    			<li>
					    			 <div class="mdl-grid">
					    				<div class="mdl-cell mdl-cell--12-col">
					    					<span class="icon-grin item"></span>
					    					<a class="detail_content_name"  href="{{ level.id }}">{{ level.name }}</a>
					    				</div>
					    			 </div>
					    			</li>
				    			{% endfor %}
			    			</ul>
			    		</div>
			    		<br>

		    		</div>

				{% endfor %}

				


	    	</div>
  			<div class="mdl-cell mdl-cell--2-col"></div>

	    	
		</div>
	  </main>
	</div>

    


</body>

adminProgrammingGame/gameProgramming/templates/gameProgramming/level_detail.html
<!-- <h1>{{ object.name }}</h1> -->

{% load staticfiles %}

<html>
<head>
	<title>Prototipo con Blocky</title>

	<script src = "{% static "gameProgramming/lib/js/easeljs-0.8.2.min.js" %}"  type="text/javascript"></script>
	<script src = "{% static "gameProgramming/lib/js/tweenjs-NEXT.combined.js" %}"  type="text/javascript"></script>
	<link rel = "stylesheet" href = "{% static "gameProgramming/lib/css/material.min.css" %}"></link>
	<link rel = "stylesheet" href = "{% static "gameProgramming/statics/css/styleGame.css" %}"></link>
	<link rel = "stylesheet" href = "{% static "gameProgramming/lib/font/icons.css" %}"></link>
	
</head>
<body>	

	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	  <!-- <div class='modal_instruction'></div> -->
	  <header id = "mainHeader" class="mdl-layout__header">
	    <div class="mdl-layout__header-row">
	      
	      <span class="mdl-layout-title">Prototipo con Blocky</span>
	      
	      </nav>
	    </div>
	  </header>
	    			
	  
	  <main class="mdl-layout__content">
	    <div class="page-content">
	    	<div class="mdl-grid">

	    	<div class="mdl-cell mdl-cell--4-col">
	    		<div id="placeToPlay">
	    			<canvas id="c" style="
					    width: 100%;
					    height: 100%;">
					</canvas>
	    		</div>
	    		<div id="execute">
	    			<button id="buttonExecute" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
					  Ejecutar
					</button>
	    		</div>
			</div>

			<div class="mdl-cell mdl-cell--8-col">

			  <div id="blocklyDiv">

				
			  </div>
			 	
			</div>	

			
	    </div>
	  </main>
	</div>
	<div id="gameMap" style="display:none" data-map ="{{ object.gameMap }}"></div>		  
			
	<dialog class="mdl-dialog">
    <h4 class="mdl-dialog__title">{{ object.name }}</h4>
    <div class="mdl-dialog__content">
      <p class = "instruction">
        {{ object.instruction }}
      </p>
    </div>
    <div class="mdl-dialog__actions">
      <button type="button" class="mdl-button close">Cerrar</button>
    </div>
  </dialog>

  <dialog id="winDialog" class="mdl-dialog">
    <h5 class="mdl-dialog__title">¡Felicidades. Has completado el nivel!</h5>
    
    <div class="mdl-dialog__content">
      <p class = "instruction">
        Vas por el camino correcto, continua divirtiendote y desarrollando tus habilidades.
      </p>
    </div>

    <div class="mdl-dialog__actions">
    	{% if object.nextLevel %}
      		<a class="btn_nextLevel" href="/{{ object.nextLevel.id }}/">Siguiente Nivel</a>
	    {% else %}
      		<a  class="btn_nextLevel"href="/">El juego Ha terminado :>D</a>
	    {% endif %}
    </div>
  </dialog>

  <dialog id="loseDialog" class="mdl-dialog">
    <h5 class="mdl-dialog__title">¡No te Rindas!</h5>
    
    <div class="mdl-dialog__content">
      <p class = "instruction">
        Recuerda que debes variar la posición hacia la que se va a desplazar el personaje dede el menu desplegable. Además verifica que la cantidad de bloques sea la correcta.
      </p>
    </div>

    
    <div class="mdl-dialog__actions">
      <button type="button" class="mdl-button close">Cerrar</button>
    </div>
  </dialog>

	 <xml id="toolbox" style="display: none">
	 	{% for control in object.control_set.all %}
	  		<block type="{{control.name}}"></block>
	 	{% endfor %}

	 <!--  <block type="math_number"></block>
	  <block type="controls_if"></block>
	  <block type="blk_movement"></block>
   	  <block type="logic_compare"></block>
      <block type="controls_repeat_ext"></block>
      <block type="text"></block>
      <block type="text_print"></block> -->

	</xml>


	<script src = "{% static "gameProgramming/lib/js/jquery-1.12.2.min.js" %}"  type="text/javascript"></script>
	<script src="{% static "gameProgramming/lib/js/acorn_interpreter.js" %}" type="text/javascript"></script>
	<script src="{% static "gameProgramming/lib/blocky/blockly_compressed.js" %}" type="text/javascript"></script>
	<script src="{% static "gameProgramming/lib/blocky/blocks_compressed.js" %}" type="text/javascript"></script>
	<script src="{% static "gameProgramming/lib/blocky/es.js" %}" type="text/javascript"></script>
	<script src="{% static "gameProgramming/lib/blocky/javascript_compressed.js" %}" type="text/javascript"></script>
	
	<script src="{% static "gameProgramming/statics/js/logic.js" %}" type="text/javascript"></script>
	<script src = "{% static "gameProgramming/lib/js/material.min.js" %}"  type="text/javascript"></script>
</body>
</html>